const courses=[
 {code:'DLMITGEC01',title:'Global E-Commerce & Internet Law',ects:5,semester:3,accent:'purple',modules:['The digital commerce ecosystem','International jurisdiction and applicable law','Electronic contracts and signatures','Consumer protection in online markets','Data protection for e-commerce','Cross-border payments and fintech','Online platforms and intermediary liability','Digital content and copyright','Dispute resolution in cyberspace','Future trends in internet law']},
 {code:'DLMITDPL02',title:'Digital Platforms & Intellectual Property Regulation',ects:5,semester:3,accent:'blue',modules:['Platform economy fundamentals','Competition law and gatekeepers','Copyright in digital environments','Trade marks and platform branding','Patent strategy for technology firms','Open source and software licensing','User-generated content','AI-generated works and ownership','Enforcement across borders','Regulatory strategy workshop']},
 {code:'DLMBCAML01',title:'International Financial Crime & AML Standards',ects:5,semester:3,accent:'green',grade:12,modules:['Financial crime typologies','FATF recommendations','Money laundering offences','Terrorist financing controls','Sanctions and export controls','Suspicious transaction reporting','Investigation and asset recovery','AML governance and controls','International cooperation','Case study: complex financial networks']},
 {code:'DLMBCKYC02',title:'Risk Management & KYC Compliance Frameworks',ects:5,semester:3,grade:15,modules:['Risk-based compliance models','Customer identification programmes','Enhanced due diligence','Beneficial ownership','PEP and sanctions screening','Transaction monitoring','Third-party risk','RegTech and automation','Audit and assurance','Building a compliance culture']},
 {code:'DLMBITDL01',title:'International Tax Law & Transfer Pricing',ects:5,semester:3,grade:14.5,modules:['International tax principles','Residence and source taxation','Double tax treaties','Arm’s length principle','Transfer pricing methods','Intra-group services','Intangibles and cost sharing','Dispute resolution','Documentation and reporting','Practical transfer pricing review']},
 {code:'DLMBIDT02',title:'Global Digital Taxation & Corporate Tax Planning',ects:5,semester:3,grade:16,modules:['Digital business models and tax','Permanent establishment online','Pillar One and Pillar Two','VAT on digital services','Withholding tax','Corporate tax planning principles','Anti-abuse rules','Tax technology and data','Ethics of tax planning','Capstone planning exercise']},
 {code:'DLMLTCS01',title:'Legal Tech & Corporate Practice Seminar',ects:5,semester:4,grade:13,modules:['Legal operations and innovation','Document automation','Contract lifecycle management','Legal research technology','AI and professional responsibility','Cybersecurity for legal teams','Data analytics for counsel','Project management in practice','Innovation lab','Professional practice presentation']}
];
const grades={DLMBCAML01:12,DLMBCKYC02:15,DLMBITDL01:14.5,DLMBIDT02:16,DLMLTCS01:13,DLMITGEC01:15};
function card(course){return `<article class="course-card"><div class="course-top"><span class="course-code">${course.code}</span><span class="credits">${course.ects} ECTS</span></div><h3>${course.title}</h3><small>${course.modules.length} learning modules · 100+ page course pack</small><button class="open-course" data-course="${course.code}">Open course →</button></article>`}
function render(){document.getElementById('coursePreview').innerHTML=courses.slice(0,3).map(card).join('');document.getElementById('semester3').innerHTML=courses.filter(c=>c.semester===3).map(card).join('');document.getElementById('semester4').innerHTML=courses.filter(c=>c.semester===4).map(card).join('');document.getElementById('transcriptRows').innerHTML=courses.filter(c=>c.semester===3).map(c=>`<div class="table-row"><span>${c.code}<br /><small>${c.title}</small></span><span>${c.ects}</span><span class="grade">${grades[c.code]}</span><span class="pass">Validated</span></div>`).join('')}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById(id).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.getElementById('currentPage').textContent=id==='dashboard'?'Dashboard':id==='courses'?'My Courses':id==='transcript'?'Transcript':id==='thesis'?'Master Thesis':'Certificate';window.scrollTo(0,0);document.getElementById('sidebar').classList.remove('open')}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)showView(nav.dataset.view);const course=e.target.closest('[data-course]');if(course){const c=courses.find(x=>x.code===course.dataset.course);document.getElementById('modalContent').innerHTML=`<p class="eyebrow">${c.code} · ${c.ects} ECTS</p><h2>${c.title}</h2><p class="modal-note">This course is designed as a structured 100+ page learning pack. Complete each module, review the readings and submit the associated assessment through the learning platform.</p><h3>Course modules</h3>${c.modules.map((m,i)=>`<div class="module"><strong>${String(i+1).padStart(2,'0')} &nbsp; ${m}</strong><span>Reading · 10 pages</span></div>`).join('')}`;document.getElementById('courseModal').classList.add('show')}});document.getElementById('modalClose').onclick=()=>document.getElementById('courseModal').classList.remove('show');document.getElementById('courseModal').onclick=e=>{if(e.target.id==='courseModal')e.currentTarget.classList.remove('show')};document.getElementById('menuToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');render();
